#!/bin/bash
# shellcheck disable=SC2059,SC1091

go_install() {

    # Download Go 
    curl -fsSL -o /tmp/go1.21.1.linux-amd64.tar.gz \
         https://go.dev/dl/go1.21.1.linux-amd64.tar.gz || 
            printf "There was a problem downloading Go.\n" && return 1

    # Extract Go
    [[ -f /tmp/go1.21.1.linux-amd64.tar.gz ]] && 
        sudo tar -C /usr/local -xzf /tmp/go1.21.1.linux-amd64.tar.gz ||
            printf "There was a problem unzipping the Go tarball.\n" >&2 && return 1

    # Add Go to PATH if it's not already
    go_path_exists=false
    for file in ~/.bash*; do
        if [[ $file == "$HOME/.bash_history" ]] || [[ $file == "$HOME/.bash_logout" ]]; then
            continue
        fi
        if grep -q "/usr/local/go/bin" "$file"; then
            printf "Go already exists in PATH.\n"
            go_path_exists=true
        fi
    done

    if ! $go_path_exists; then
        printf "Adding Go to PATH...\n"
        printf "export PATH=\$PATH:/usr/local/go/bin\n" >> ~/.bashrc
        printf "Go added to PATH.\n"
    fi

    # Reload bash
    source "$HOME/.bashrc"

    # Confirm Installation
    if go version; then
        printf "\e[32mGo was successfully installed.\e[0m\n"
        return 0
    fi
    printf "There was a problem downloading Go.\n"
    return 1
}

if ! go_install; then
    printf "Could not install Go.\n"
    exit 1
fi

