#!/bin/bash


install_libssl1.1() {
    curl -fsSL -o /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
    if [[ -f /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb ]]; then
        printf "Download successful, attempting to install libssl1.1\n"
        if sudo dpkg -i /tmp/libssl1.1_1.1.0g-2ubuntu4_amd64.deb; then
            printf "Install was successful.\n"
        fi
    else
        printf "There was a problem downloading libssl1.1"
    fi
}

install_libssl1.1
