#!/bin/bash
# Wrapper script for GNU Stow. Only stow directories, not files in root dir.
# TODO: Move away from relying on stow
# ln -s -t ~ <dotfile>

[[ ! -d "$HOME/.vim/autoload" ]] && mkdir -p "$HOME/.vim/autoload"
[[ ! -d "$HOME/.config" ]] && mkdir -p "$HOME/.config"

declare -a DIRS

IFS=$'\n' read -r -d '' -a DIRS < <(find . -maxdepth 1 -type d)
printf "Number of directories in DIRS: %s \n" "${#DIRS[@]}"

for d in "${DIRS[@]}"; do
    d="${d##*/}"
    [[ "$d" =~ (^\./\.|^\.) ]] && printf "Skipping hidden directory: %s\n" "$d" && continue
    printf "Directory being stowed: %s \n" "$d"
    stow -R "$d" || {
        printf >&2 "[ERROR]: Unable to stow directory: %s\n" "$d"
        continue
    }
done

