#!/bin/bash

declare -a FILES
IFS=$'\n' read -r -d '' -a FILES < <(find ~/.dotfiles/ -type f ! -path '*.git*')

for f in "${FILES[@]}"; do
    tr -d '\r' < "$f" > "${f}_lf"
    mv "${f}_lf" "$f"
done

