#!/bin/bash


while read -r dotfile_directory; do
    echo "${dotfile_directory//.dotfiles\//}"
    final_destination="${dotfile_directory/#$HOME\/.dotfiles/}"
    # final_destination="${final_destination//$dotfile_directory/}"
    printf "Dotfile Directory: %s\nFinal Destination:%s\n" "$dotfile_directory" "$final_destination"
done < <(find ~/.dotfiles/ -mindepth 1 -maxdepth 1 -type d ! -name '.git')

declare -a DIRS
IFS=$'\n' read -d '' -r -a DIRS < <(find ~/.dotfiles/ -mindepth 1 -maxdepth 1 -type d ! -name '.git')

for d in "${DIRS[@]}"; do
    declare -a SUBDIRS
    IFS=$'\n' read -d '' -r -a SUBDIRS < <(find "$d" -mindepth 1 -maxdepth 1 -type d)

    declare -a FILES
    # find "$d" -mindepth 1 -type f -exec ln -sf '{}' "${HOME}/${}" \;
    IFS=$'\n' read -d '' -r -a FILES < <(find "$d" -mindepth 1 -type f)
    for f in "${FILES[@]}"; do
        printf "Looking at file: %s\n" "$(basename "$f")"
        final_destination="${d/#$HOME\/.dotfiles/$HOME}"
        printf "Final destination: %s\n" "$final_destination"
        # ln -s "$f" "$HOME"
    done
done







