#!/bin/bash


go_install() {

    # Make installation directory
    mkdir -p ~/install/go
    cd ~/install/go

    # Download Go ()
    if [[ ! -f ~/install/go/go1.21.1.linux-amd64.tar.gz ]]; then
        echo "tarball not found, downloading."
        wget https://go.dev/dl/go1.21.1.linux-amd64.tar.gz
    fi

    # Check that the download succeeded
    if [[ -f ~/install/go/go1.21.1.linux-amd64.tar.gz ]]; then
        # Extract Go
        sudo tar -C /usr/local -xzf go1.21.1.linux-amd64.tar.gz

        # Add Go to PATH if it's not already
        go_path_exists=false
        for file in ~/.bash*; do
            if [[ $file == "~/.bash_history" ]] || [[ $file == "~/.bash_logout" ]]; then
                continue
            fi
            if grep -q "export PATH=\$PATH:/usr/local/go/bin" "$file"; then
                go_path_exists=true
            fi
        done

        if ! $go_path_exists; then
            echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.bashrc
        fi

        # Reload bash
        source ~/.bashrc

        # Confirm Installation
        go version
    else
        echo "There was a problem downloading Go."
    fi
}

go_install
