#!/bin/bash

note_files=$(find . -name '*.md')
existing=0
if [[ -z "$NOTES_HOME" ]]; then
    echo "NOTES_HOME=\"${HOME}/notes\"" >> ~/.bash_aliases
fi
# Add the first header1 (#) 
# Should I add all headers? Maybe.
for f in $note_files; do
    if grep -q "$f" "${NOTES_HOME}/contents.md"; then
        existing+=1
        continue
    fi
done
        

